/**
 * DO NOT EDIT THIS FILE.
 * See the following change record for more information,
 * https://www.drupal.org/node/2815083
 *
 * @preserve
 **/

(function ($, Drupal) {
  Drupal.behaviors.banner = {
    attach: function (context, settings) {
      document.querySelectorAll(".card-show").forEach(function (card) {
        card.style.display = "none";
      });

      var no_of_card = document.getElementById("no_of_card").value;
      for (let i = 1; i <= no_of_card; i++) {
        document.getElementById("card" + i).style.display = "block";
      }

      document.getElementById("no_of_card").addEventListener("change", function () {
        document.querySelectorAll(".card-show").forEach(function (card) {
          card.style.display = "none";
        });

        var no_of_card = document.getElementById("no_of_card").value;
        for (let i = 1; i <= no_of_card; i++) {
          document.getElementById("card" + i).style.display = "block";
        }
      });
    }
  };
})(jQuery, Drupal);
